#!productName=Drools

#!productVersion=9.105.0

#!droolsProductVersion={{productVersion}}
#!versionDroolsOverrideProduct=-DversionOverride={{droolsProductVersion}}

#!quarkusVersionCommunity=3.27.3
#!quarkusVersion={{quarkusVersionCommunity}}.redhat-00002

#!milestone=CR1
#!stage=GA
#!scmRevision=9.105.x-prod

#!gitServer=github.com

#!npm_registry=http://indy-admin.psi.redhat.com/api/folo/track/\$buildContentId/npm/remote/npmjs/
#!node_download=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/
#!npm_download=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/npm/
#!yarn_download=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/yarn/
#!configureNpmRegistry=echo registry={{npm_registry}} > ~/.npmrc; echo fetch-timeout=3600000 >> ~/.npmrc

#!baseMaven={{configureNpmRegistry}}; mvn deploy -B -Dmaven.test.failure.ignore=true -Drevapi.skip=true -Denforcer.skip=true -Dgwt.compiler.localWorkers=1 -Dproductized=true -DskipTests=true -Dfindbugs.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -Dmaven.artifact.threads=25 -DnpmRegistryURL={{npm_registry}} -DnodeDownloadRoot={{node_download}} -DnpmDownloadRoot={{npm_download}} -DyarnDownloadRoot={{yarn_download}}
#!baseMavenTree={{baseMaven}} dependency:tree

#!groovyScriptBase=https://gitlab.cee.redhat.com/middleware/build-configurations/raw/master/drools/{{productVersion}}

#!pmeAddProjectSources=-DprojectSrcSkip=false -DenabledDeprecatedProperties=true

product:
  name: {{productName}}
  abbreviation: drools
  stage: {{stage}}
  issueTrackerUrl: http://issues.jboss.org/browse/DROOLS
version: {{productVersion}}
milestone: {{milestone}}
group: {{productName}}-{{productVersion}}-{{milestone}}-all
defaultBuildParameters:
  project: drools
  environmentId: 1664 # "OpenJDK 17.0; RHEL 9; Mvn 3.9.11"
  buildScript: {{baseMavenTree}}
builds:
  - name: org.drools-drools-{{droolsProductVersion}}
    project: kiegroup/drools
    scmUrl: https://{{gitServer}}/kiegroup/drools.git
    scmRevision:  {{scmRevision}}
    alignmentParameters:
      - '{{versionDroolsOverrideProduct}}'
      - '-DquarkusVersion={{quarkusVersion}}'
      - '-DgroovyScripts={{groovyScriptBase}}/SetQuarkusVersion.groovy'
      - '{{pmeAddProjectSources}}'

outputPrefixes:
  releaseFile: drools
  releaseDir: drools

flow:
  licensesGeneration:
    strategy: IGNORE

  repositoryGeneration:
    strategy: IGNORE

  javadocGeneration:
    strategy: IGNORE

  sourcesGeneration:
    strategy: IGNORE
